Create logger for debuging #1
darts-plus/darts-plus-embedded pull request #5
Opened 2022-03-11 21:31 UTC by xHeler

- Add ArduinoLog library
- Modify platformio.ini to adapt for colored terminal info

2022-03-11 23:22 UTC, delipl requested changes
In the original library, the colors are not implemented.
Make submodule from your fork

2022-03-11 23:54 UTC, delipl approved these changes

2022-03-12 17:58 UTC, GrzegorzWojnarowicz approved these changes

2022-03-13 18:13 UTC, Selvan66 approved these changes

2022-03-13 22:25 UTC, ArturZiolkowski1999 approved these changes

2022-03-14 07:48 UTC, GrzegorzWojnarowicz approved these changes

2022-03-15 18:06 UTC, OlafBieganski approved these changes

2022-03-15 18:47 UTC, merged